version: '3'

services:

  db:
    image: 'mysql:latest'
    ports:
      - "3301:3306"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /my/own/datadir:/var/lib/mysql
